version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Setup a virtualenv
          command: virtualenv venv
      - run:
          name: Install tox
          command: |
            source venv/bin/activate
            pip install tox
      - run:
          name: Run tests with tox
          command: |
            source venv/bin/activate
            tox
