version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    environment:
      - DJANGO_VERSIONS: "18;19;110;111"
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Update and install OS packages
          command: |
            sudo apt-get update
            sudo apt-get install libxmlsec1-dev
      - run:
          name: Setup a virtualenv
          command: virtualenv venv
      - run:
          name: Install tox
          command: |
            source venv/bin/activate
            pip install tox
      - run:
          name: Run tests with tox
          command: |
            source venv/bin/activate
            echo $DJANGO_VERSIONS | tr ";" "\n" | xargs -L 1 -I % tox -e dj%
