version: 2
jobs:
  lint-checks:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Setup a virtualenv
          command: virtualenv venv
      - run:
          name: Install linters and custom checkers
          command: |
            source venv/bin/activate
            pip install flake8 pylint sentry-stack-checker==0.3 flake8-import-order git+ssh://git@github.com/infoscout/isc-style-guide@0.2.2
      - run:
          name: Lint with flake8
          command: |
            source venv/bin/activate
            flake8 --exclude=.git,__pycache__,.tox,*/migrations/*
      - run:
          name: Lint with Pylint (custom checks)
          command: |
            source venv/bin/activate
            PYTHONPATH=/usr/local/lib/python3.6/site-packages/isc_style_guide/checkers pylint
    build:
      docker:
        - image: circleci/python:2.7
      steps:
        - checkout
        - run:
            name: Setup a virtualenv
            command: virtualenv venv
        - run:
            name: Install tox
            command: |
              source venv/bin/activate
              pip install tox
        - run:
            name: Run tests with tox
            command: |
              source venv/bin/activate
              tox

workflows:
  version: 2
  build-and-lintcheck:
    jobs:
      - lint-checks
      - build:
          requires:
            - lint-checks
